# Generated by Django 4.2.16 on 2026-08-15 17:02

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number.', regex='^[6-9]\\d{9}$')])),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit pincode.', regex='^\\d{6}$')])),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('opening_time', models.TimeField(default=datetime.time(9, 0))),
                ('closing_time', models.TimeField(default=datetime.time(21, 0))),
                ('image', models.ImageField(blank=True, null=True, upload_to='shops/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=12)),
                ('status_reason', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=25, max_digits=7)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('avg_prep_minutes', models.PositiveIntegerField(default=15)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('is_accepting_orders', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='catalog.category')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopKyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(blank=True, max_length=180)),
                ('license_type', models.CharField(choices=[('FSSAI', 'FSSAI (food)'), ('SHOP_ESTABLISHMENT', 'Shop & establishment'), ('TRADE_LICENSE', 'Trade license'), ('DRUG_LICENSE', 'Drug license'), ('NONE', 'Not applicable')], default='NONE', max_length=24)),
                ('license_number', models.CharField(blank=True, max_length=60)),
                ('gst_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number.', regex='^$|^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('pan_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number.', regex='^$|^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('bank_account_name', models.CharField(blank=True, max_length=120)),
                ('bank_account_number', models.CharField(blank=True, max_length=24)),
                ('bank_ifsc', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code.', regex='^$|^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('license_document', models.FileField(blank=True, null=True, upload_to='kyc/')),
                ('extra_details', models.JSONField(blank=True, default=dict, help_text='Category-specific fields that differ per business type.')),
                ('is_verified', models.BooleanField(default=False)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Shop KYC',
                'verbose_name_plural': 'Shop KYC',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['status', 'city'], name='shops_shop_status_43fc36_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['latitude', 'longitude'], name='shops_shop_latitud_e4840a_idx'),
        ),
    ]
